; PlatformIO Project Configuration File
[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = espidf

board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.partitions = partitions/v2/16m_photo.csv

monitor_speed = 115200
